### ISSUE TITLE
Buttons don't work on some devices on Android 5.1.1

### ISSUE THREAD

**Issue by mirko77** [ImperialCollegeLondon/EpicollectPlus-mobile-client-html5#3]
The app does not work at all, it gets stuck on the home screen with all the buttons not working

Samsung Galaxy S6 Edge, Android 5.1.1

Lg G4, Android 5.1.1

**Comment by mikeb226** [comment]
any forward movement on this issue?

**Comment by mirko77** [comment]
@mikeb226 Hi this app has been deprecated so the issue will not be fixed. (We cannot reproduce the issue on the devices we have. It is a Samsung specific issue)

We will be realising a brand new platform/app soon called Epicollect5

**Comment by mikeb226** [comment]
Thank you for the quick reply!

I'm using a Moto X Pure/Style with Android 6.0

Any idea when the release of the new version will be?

The old version works fairly well, but we need iPhone compatibility. I'm
assuming there will be both Android and iOS versions with the new release?

Thanks!

~mike

**Comment by mirko77** [comment]
Yes, Android/iOS

we are currently experiencing a few issues on iOS 10.

We are planning to release a Beta before the end of the year, Android first then iOS

you can request early access [here](https://five.epicollect.net/contact) and download an apk (Android) to sideload [here](https://drive.google.com/open?id=0B6K16Oe-ZJjeYmNyQWNlYTk2RFk)
